ALTER TABLE client ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE client ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE client ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE equipment ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE equipment ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE equipment ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE technician ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE technician ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE technician ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE intervention ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE intervention ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE intervention ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
